---
- name: Handle High CPU Utilization Incident on Windows
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_user: "{{ lookup('env', 'SN_USERNAME') }}"
    servicenow_password: "{{ lookup('env', 'SN_PASSWORD') }}"
    ssh_user: "{{ lookup('env', 'SSH_USERNAME') }}"
    ssh_password: "{{ lookup('env', 'SSH_PASSWORD') }}"
    ssh_port: "22"
    domain_suffix: ".com"
    csv_host: hostname
    ack_inc: "/data/INC_CSV/cpu_incidents_ack.csv"
    time_now: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"

  tasks:

    - name: Gather facts for localhost to get date/time
      setup:
      delegate_to: localhost
      delegate_facts: yes 
    
    - name: Fetch incidents from ServiceNow
      uri:
        url: "https://service-now.com/api/now/table/incident?sysparm_query=short_descriptionLIKEALERT%20MONITORING%20--%20_Basic%20Monitoring%20-%20Server%20CPU%20Alert%20--%5Estate%3D9%5Eassignment_group%####################################%5EdescriptionLIKEWindows%5EORdescriptionLIKEHyper-V&sysparm_display_value=true"
        method: GET
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        return_content: yes
      register: incident_data
      # New: Handle potential ServiceNow API errors
      failed_when: incident_data.status != 200 or not incident_data.json.result is defined

    - name: Exit play gracefully if no incidents found
      when: incident_data.json.result | length == 0
      meta: end_play

    - name: Create list of incidents with number, hostname, and sys_id
      set_fact:
        incident_list_for_loop: >
          [ {% for item in incident_data.json.result %}
              {
                "incident_number": "{{ item.number }}",
                "hostname": "{{ item.cmdb_ci.display_value }}",
                "sys_id": "{{ item.sys_id }}"
              }{% if not loop.last %},{% endif %}
            {% endfor %} ]
      # New: Only proceed if incident_data.json.result is defined and not empty
      when: incident_data.json.result is defined and incident_data.json.result | length > 0

    - name: Process each incident
      include_tasks: Ack_and_update_INC.yml
      loop: "{{ incident_list_for_loop }}"
      loop_control:
        loop_var: current_incident_item # Renamed for clarity within the loop
        label: "{{ current_incident_item.incident_number }} -> {{ current_incident_item.hostname }}"
      # New: Only loop if incident_list_for_loop is defined (which it will be if incidents are found)
      when: incident_list_for_loop is defined and incident_list_for_loop | length > 0

    - name: Report if no incidents were processed
      debug:
        msg: "No incidents were processed due to no incidents being found or an API error."
      when: incident_list_for_loop is not defined or incident_list_for_loop | length == 0
