---
# New: Block to handle tasks for a single incident, with rescue for host-specific errors
- block:
    - name: Set  messages
      set_fact:
        message: |
          Investigating the High CPU ALert on server {{ current_incident_item.hostname }}.mcjunkinredman.com
          
    - name: Update ServiceNow incident {{ current_incident_item.incident_number }} (in-Progress)
      uri:
        url: "https://mrcglobaltest.service-now.com/api/now/table/incident/{{ current_incident_item.sys_id }}"
        method: PATCH
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        headers:
          Content-Type: "application/json"
        body: >-
          {% set body_data = {} %}
          {% set _ = body_data.update({
                      'state': '2',
                      'assigned_to': 'ansible_awx',
                      'comments': message | default('Investigating the High CPU ALert on server.')
                    }) %}
          {{ body_data | to_json }}
      register: servicenow_update_result
      failed_when: servicenow_update_result.status not in [200, 201, 202, 204]
    
    # Initialize the list to store CPU values from each poll
    - name: Initialize cpu_values_per_poll list
      set_fact:
        cpu_values_per_poll: []
      delegate_to: localhost # Ensure this runs on the controller
      run_once: true # Ensure it's initialized only once per incident process

    - name: Perform CPU polling and update ServiceNow on each poll
      include_tasks: perform_single_cpu_poll.yml # Call the new task file
      loop: "{{ range(1, poll_count | int + 1) | list }}"
      loop_control:
        loop_var: current_poll_iteration # Pass this for the poll-specific message
        pause: "{{ poll_interval }}" # Delay between each iteration (each poll and update)

    - name: Calculate average and max CPU from all polls
      set_fact:
        # cpu_values is now directly the list from `cpu_values_per_poll`
        cpu_values: "{{ cpu_values_per_poll }}"
        cpu_avg: "{{ (cpu_values_per_poll | sum / cpu_values_per_poll | length) | round(2) }}"
        cpu_max: "{{ cpu_values_per_poll | max }}"
      when: cpu_values_per_poll is defined and cpu_values_per_poll | length > 0

    - name: Analyze CPU usage (based on all polls)
      set_fact:
        cpu_ok: "{{ cpu_values | default([]) | select('lt', cpu_threshold) | list | length == poll_count }}"
      when: cpu_values is defined

    - name: get CPU top processes
      win_shell: |
        try {
            $TOP_PROCESS = Get-Process | Sort-Object -Property CPU -Descending |
              Select-Object -First 10 @{Name="ProcessName";Expression={$_.ProcessName}},
              @{Name="CPU";Expression={[math]::Round($_.CPU, 2)}},
              @{Name="MemoryMB";Expression={[math]::Round($_.WorkingSet64 / 1MB, 2)}} 

            $CPUuti = "Average: {{ cpu_avg | default('N/A') }}%"
            $CPUPER = "Max: {{ cpu_max | default('N/A') }}%"


            $tableRows = $TOP_PROCESS | ForEach-Object {
              "<tr><td>$($_.ProcessName)</td><td>$($_.CPU)</td><td>$($_.MemoryMB)</td></tr>"
            }

            $HTMLBody = "
            <html>
            <head>
            <style>
            body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #f4f4f4; }
            .container { max-width: 700px; margin: 30px auto; padding: 25px; background: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
            h2 { color: #2c3e50; }
            p { font-size: 16px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; }
            th { background-color: #3498db; color: white; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            tr:hover { background-color: #f1f1f1; }
            </style>
            </head>
            <body>
            <div class='container'>
            <h2>CPU Utilization Report for {{ current_incident_item.hostname }}</h2>
            <p><strong>Utilization Level:</strong> $CPUuti, $CPUPER</p>
            <h3>Top 10 CPU Utilized Processes</h3>
            <table>
            <tr>
            <th>Process Name</th>
            <th>CPU Time</th>
            <th>Memory Usage (MB)</th>
            </tr>
            $tableRows
            </table>
            </div>
            </body>
            </html>
            "
            Write-Output "$HTMLBody"
        } catch {
            Write-Error "Failed to get top processes: $($_.Exception.Message)"
            exit 1 # Exit with error code to indicate failure
        }
      register: cpu_top
      delegate_to: "{{ current_incident_item.hostname }}.mcjunkinredman.com"
      # New: This task is allowed to fail, and the rescue block will catch it.
      ignore_errors: true

    # NEW TASK: Log incident details to CSV
    - name: Ensure CSV log file exists
      ansible.builtin.file:
        path: "/data/INC_CSV/Windows_CPU_incidents.csv"
        state: touch
        mode: '0644'
      delegate_to: aztlrh9ansawx00.mcjunkinredman.com
      vars:
        ansible_user: "{{ SSH_USERNAME }}"
        ansible_password: "{{ SSH_PASSWORD }}"
        ansible_connection: "ssh"
        ansible_port: 22
      run_once: true # Ensure this only runs once per playbook, not per loop item

    # MODIFIED: Log incident details using shell to always append
    - name: Log incident details for upscaling analysis
      ansible.builtin.shell: |
        echo "{{ current_incident_item.hostname }},{{ current_incident_item.incident_number }},{{ ansible_date_time.iso8601 }}" >> "/data/INC_CSV/Windows_CPU_incidents.csv"
      delegate_to: aztlrh9ansawx00.mcjunkinredman.com
      vars:
        ansible_user: "{{ SSH_USERNAME }}"
        ansible_password: "{{ SSH_PASSWORD }}"
        ansible_connection: "ssh"
        ansible_port: 22
      when: not ansible_check_mode

    # NEW TASK: Read and analyze CSV for recurring alerts (Upscaling suggestion)
    - name: Check for recurring alerts for {{ current_incident_item.hostname }}
      slurp:
        src: "/data/INC_CSV/Windows_CPU_incidents.csv"
      register: cpu_incident_log
      delegate_to: aztlrh9ansawx00.mcjunkinredman.com
      vars:
        ansible_user: "{{ SSH_USERNAME }}"
        ansible_password: "{{ SSH_PASSWORD }}"
        ansible_connection: "ssh"
        ansible_port: 22
      when: not ansible_check_mode

    - name: Process CSV data - Decode and Split Lines
      set_fact:
        # This will create a list where each element is a line from the CSV
        decoded_csv_lines: "{{ cpu_incident_log.content | b64decode | split('\n') }}"
      when: cpu_incident_log.content is defined and not ansible_check_mode

    - name: Process CSV data - Filter for Server Alerts
      set_fact:
        # This will filter the lines to only include those matching the current hostname
        server_alerts: "{{ decoded_csv_lines | select('match', '^' + current_incident_item.hostname + ',') | list }}"
      # Only run if decoded_csv_lines was successfully set in the previous step
      when: decoded_csv_lines is defined and not ansible_check_mode

    - name: Process CSV data - Calculate Alert Count
      set_fact:
        # This calculates the length of the filtered list
        #alert_count: "1"
        alert_count: "{{ server_alerts | length }}"
      # Only run if server_alerts was successfully set in the previous step
      when: server_alerts is defined and not ansible_check_mode

    # - name: Suggest upscaling if alert count exceeds threshold
    #   block:
    #     - name: Send email for upscaling suggestion
    #       ansible.builtin.mail:
    #         host: mail1.mcjunkinredman.com
    #         from: Godwin.Monickaraj@mrcglobal.com
    #         to: Vinodkumar.Jeerangi@mrcglobal.com, Godwin.Monickaraj@mrcglobal.com
    #         subject: "Action Required: High CPU Alerts - Server Upscaling Suggestion for {{ current_incident_item.hostname }}"
    #         body: |
    #           Dear Team,

    #           This is an automated alert from Ansible AWX.
    #           We have observed {{ alert_count }} high CPU incidents for the server '{{ current_incident_item.hostname }}' over a period of time.
    #           The current incident ID is {{ current_incident_item.incident_number }}.

    #           This recurring pattern suggests that the server may be undersized for its workload.
    #           We recommend reviewing the server's resource utilization and considering an upgrade (e.g., adding more CPU cores or increasing clock speed).

    #           Please investigate further to prevent future performance degradation and incidents.

    #           Best Regards,
    #           Ansible Automation
    #       delegate_to: aztlrh9ansawx00.mcjunkinredman.com
    #       when: alert_count | int >= 3 # Threshold for upscaling suggestion (e.g., 3 or more incidents)

      #   - name: Add work note to ServiceNow incident for upscaling suggestion
      #     uri:
      #       url: "https://mrcglobaltest.service-now.com/api/now/table/incident/{{ current_incident_item.sys_id }}"
      #       method: PATCH
      #       user: "{{ servicenow_user }}"
      #       password: "{{ servicenow_password }}"
      #       force_basic_auth: yes
      #       body_format: json
      #       headers:
      #         Content-Type: "application/json"
      #       body:
      #         work_notes: |
      #           Automated suggestion: This server ({{ current_incident_item.hostname }}) has triggered high CPU alerts {{ alert_count }} times.
      #           Consider reviewing its specifications for a potential upgrade to prevent recurring incidents.
      #     register: servicenow_upscale_worknote_result
      #     failed_when: servicenow_upscale_worknote_result.status not in [200, 201, 202, 204]
      #     when: alert_count | int >= 3 # Threshold for upscaling suggestion (e.g., 3 or more incidents)
      # when: alert_count is defined and alert_count | int >= 3 # Only run this block if upscaling is suggested
    - name: Set resolution/comment messages
      set_fact:
        resolution_message: |
          Automated resolution: CPU normalized for {{ current_incident_item.hostname }}.
          Average CPU over {{ poll_count }} polls: {{ cpu_avg | default('N/A') }}%.
          Max CPU during polls: {{ cpu_max | default('N/A') }}%.
          [code]
          {{ cpu_top.stdout | default('Failed to retrieve top processes.') }}
          [/code]
        comment_message: |
          CPU still high on {{ current_incident_item.hostname }}, investigation needed.
          Average CPU over {{ poll_count }} polls: {{ cpu_avg | default('N/A') }}%.
          Max CPU during polls: {{ cpu_max | default('N/A') }}%.
          Moving the Incident to new state again.

          [code]
          {{ cpu_top.stdout | default('Failed to retrieve top processes.') }}
          [/code]
      # Only run this if cpu_ok is defined (from analyze CPU usage) or cpu_top is registered
      when: (cpu_ok is defined or (cpu_top is defined and cpu_top.stdout is defined)) and alert_count is defined and alert_count | int < 3 

    - name: Set resolution/comment messages
      set_fact:
        comment_message: |
          CPU normalized, but recurring high CPU alerts detected. Investigation needed for potential upscaling.
          Average CPU over {{ poll_count }} polls: {{ cpu_avg | default('N/A') }}%.
          Max CPU during polls: {{ cpu_max | default('N/A') }}%.
          Moving the Incident to new state again.

          [code]
          {{ cpu_top.stdout | default('Failed to retrieve top processes.') }}
          [/code]
      # Only run this if cpu_ok is defined (from analyze CPU usage) or cpu_top is registered
      when: (cpu_ok is defined or (cpu_top is defined and cpu_top.stdout is defined)) and alert_count is defined and alert_count | int >=3

    - name: Update ServiceNow incident {{ current_incident_item.incident_number }} (Success Path)
      uri:
        url: "https://mrcglobaltest.service-now.com/api/now/table/incident/{{ current_incident_item.sys_id }}"
        method: PATCH
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        headers:
          Content-Type: "application/json"
        body: >-
          {% set body_data = {} %}
          {% if cpu_ok | default(false) and (alert_count is not defined or alert_count | int < 3) %}
            {% set _ = body_data.update({
                        'state': '6',
                        'assigned_to': 'ansible_awx',
                        'u_caused_by_a_change': 'no',
                        'close_code': 'Solved (Permanently)',
                        'close_notes': resolution_message | default('Automated resolution: CPU normalized.'),
                        'work_notes': resolution_message | default('Automated resolution: CPU normalized.')
                      }) %}
          {% elif alert_count is defined and alert_count | int >= 3 %}
            {% set _ = body_data.update({
                        'state': '9', 
                        'assigned_to': '',
                        'comments': comment_message | default('CPU normalized, but recurring high CPU alerts detected. Investigation needed for potential upscaling.'),
                        'work_notes': comment_message | default('CPU normalized, but recurring high CPU alerts detected. Investigation needed for potential upscaling.')
                      }) %}
          {% else %}
            {% set _ = body_data.update({
                        'state': '9',
                        'assigned_to': '',
                        'comments': comment_message | default('CPU still high, investigation needed.')
                      }) %}
          {% endif %}
          {{ body_data | to_json }}
      register: servicenow_update_result
      failed_when: servicenow_update_result.status not in [200, 201, 202, 204]

  # New: Rescue block for host-specific errors (network, win_shell failures)
  rescue:
    - name: Update ServiceNow incident {{ current_incident_item.incident_number }} (Error Path)
      uri:
        url: "https://mrcglobaltest.service-now.com/api/now/table/incident/{{ current_incident_item.sys_id }}"
        method: PATCH
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          state: "9"
          assigned_to: ''
          comments: |
            Failed to process incident {{ current_incident_item.incident_number }} for host {{ current_incident_item.hostname }}.
            Possible reasons:
            - Host unreachable or WinRM connection failed.
            - PowerShell command execution failed on the host.
            Please investigate manually.
            Error details: {{ ansible_failed_result | default('No specific error details available.') | to_json }}
      register: servicenow_error_update_result
      # Ensure this update attempt doesn't fail the playbook completely
      ignore_errors: true
      when: current_incident_item.sys_id is defined # Only attempt if sys_id is available
